### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by Thrqureshi** [ishaga-bello/short-quote-video-creator#1]
I am getting this error when trying to run main.py

AttributeError: 'NoneType' object has no attribute 'get'

Is there any instruction on how to run this script

**Comment by Thrqureshi** [comment]
error

(env) C:\Users\User\Desktop\Python\short-quote-video-creator>main.py
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Python\short-quote-video-creator\main.py", line 17, in <module>
    create_image(term)
  File "C:\Users\User\Desktop\Python\short-quote-video-creator\textOnImage.py", line 61, in create_image
    image_dict = imageGraber.image_graber(term)
  File "C:\Users\User\Desktop\Python\short-quote-video-creator\imageGraber.py", line 25, in image_graber
    photos = pu.photos(type_='random', count=number_of_image, featured=True, query=term, orientation='portrait')
  File "C:\Users\User\Desktop\Python\short-quote-video-creator\env\lib\site-packages\pyunsplash\pyunsplash.py", line 52, in photos
    return f(api_key=self._api_key, **kwargs)
  File "C:\Users\User\Desktop\Python\short-quote-video-creator\env\lib\site-packages\pyunsplash\src\photos.py", line 46, in __init__
    super(RandomPhotos, self).__init__(url=url, api_key=api_key, valid_options=valid_options, **kwargs)
  File "C:\Users\User\Desktop\Python\short-quote-video-creator\env\lib\site-packages\pyunsplash\src\unpage.py", line 47, in __init__
    r = self._agent.get(self.url, self.query_parameters)
AttributeError: 'NoneType' object has no attribute 'get'

(env) C:\Users\User\Desktop\Python\short-quote-video-creator>

**Comment by ishaga-bello** [comment]
hey @Thrqureshi sorry for the late reply, the issue is surely that you did not create an unsplash API key, checkout this guide [how to get an unsplash api key](https://medium.com/unsplash/unsplashs-api-8b20043aacc0) for more help and then create a file named ".env" in your root directory.
